// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var KrxData = require("./KrxData.bs.js");
var Express = require("express");

var app = Express();

var router = Express.Router();

router.use(function (req, _res, next) {
      console.log(req);
      Curry._1(next, undefined);
    });

router.use(function (err, _req, res, _next) {
      console.error(err);
      res.status(500).end("An error occured!");
    });

app.use("/someRoute", router);

app.use(Express.json());

app.get("/", (function (req, res) {
        res.status(200).json({
              meesage: "success2!!"
            });
      }));

app.get("/stock/", KrxData.getStockPriceInfoTest);

app.get("/stock-name/", KrxData.getStockPriceInfoByName);

app.post("/ping", (function (req, res) {
        var body = req.body;
        var name = body.name;
        if (name == null) {
          res.status(400).json({
                error: "Missing name"
              });
        } else {
          res.status(200).json({
                message: "Hello " + name + ""
              });
        }
      }));

app.use(function (err, _req, res, _next) {
      console.error(err);
      res.status(500).end("An error occured");
    });

app.listen(8081, (function (param) {
        console.log("Listening on http://localhost:" + String(8081) + "");
      }));

var port = 8081;

exports.app = app;
exports.router = router;
exports.port = port;
/* app Not a pure module */
