# Generated by Django 4.1.2 on 2022-10-26 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="stockKR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=40)),
                ("category", models.CharField(max_length=20)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="krStockElementModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_price", models.IntegerField()),
                ("end_price", models.IntegerField()),
                ("high_price", models.IntegerField()),
                ("low_price", models.IntegerField()),
                ("trade_quant", models.IntegerField()),
                ("trade_money", models.IntegerField()),
                ("total_stock_count", models.IntegerField()),
                ("total_comp_price", models.IntegerField()),
                (
                    "stockType",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_element",
                        to="stockKR.stockkr",
                    ),
                ),
            ],
        ),
    ]
