# Generated by Django 4.1.2 on 2022-10-27 01:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("stockKR", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="krstockelementmodel",
            old_name="stockType",
            new_name="stock_type",
        ),
        migrations.AddField(
            model_name="stockkr",
            name="isin_code",
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stockkr",
            name="short_code",
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
