// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Axios = require("axios");
var Dotenv = require("dotenv");
var $$Promise = require("reason-promise/src/js/promise.bs.js");
var Js_string = require("rescript/lib/js/js_string.js");

Dotenv.config();

var kRX_KEY = process.env.KRX_DATA_KEY;

function headers(param) {
  return {
          Host: "apis.data.go.kr",
          "Content-Type": "application/json",
          "User-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
        };
}

var config = {
  headers: {
    Host: "apis.data.go.kr",
    "Content-Type": "application/json",
    "User-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
  },
  timeout: 5000
};

var baseURL = "https://apis.data.go.kr/1160100/service/GetStockSecuritiesInfoService/getStockPriceInfo?serviceKey=" + kRX_KEY + "&resultType=json";

function getStockPriceInfoTest(_req, res) {
  $$Promise.tapError($$Promise.mapOk($$Promise.Js.toResult(Axios.get(baseURL, config)), (function (param) {
              var data = param.data;
              console.log(data.response.body.items);
              return res.status(200).json(data.response.body.items);
            })), (function (err) {
          var e = err.response;
          if (e !== undefined && e.status === 404) {
            console.log("Not found");
          } else {
            console.log("an error occured", e);
          }
        }));
}

function getStockPriceInfoByName(req, res) {
  var reqQuery = req.query;
  var url = Js_string.concatMany(["&itmsNm=" + reqQuery.name + ""], baseURL);
  $$Promise.tapError($$Promise.mapOk($$Promise.Js.toResult(Axios.get(url, config)), (function (param) {
              res.set("Access-Control-Allow-Origin", "http://localhost:8080");
              res.status(200).json(param.data);
            })), (function (err) {
          var e = err.response;
          if (e !== undefined && e.status === 404) {
            console.log("Not found");
          } else {
            console.log("an error occured", e);
          }
        }));
}

exports.kRX_KEY = kRX_KEY;
exports.headers = headers;
exports.config = config;
exports.baseURL = baseURL;
exports.getStockPriceInfoTest = getStockPriceInfoTest;
exports.getStockPriceInfoByName = getStockPriceInfoByName;
/*  Not a pure module */
