// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import LogoSvg from "./logo.svg";

var logo = LogoSvg;

import './App.css';
;

function App(Props) {
  var match = React.useState(function () {
        return 0;
      });
  var setCount = match[1];
  React.useEffect((function () {
          var intervalId = setInterval((function (param) {
                  Curry._1(setCount, (function (count) {
                          return count + 1;
                        }));
                }), 100);
          return (function (param) {
                    clearInterval(intervalId);
                  });
        }), []);
  return React.createElement("div", {
              className: "App"
            }, React.createElement("header", {
                  className: "App-header"
                }, React.createElement("img", {
                      className: "App-logo",
                      alt: "logo",
                      src: logo
                    }), React.createElement("p", undefined, "Edit ", React.createElement("code", undefined, "src/App.jsx"), " and save to reload."), React.createElement("p", undefined, "Page has been open for ", React.createElement("code", undefined, (match[0] / 10).toFixed(1)), " seconds"), React.createElement("a", {
                      className: "App-link",
                      href: "https://reactjs.org",
                      rel: "noopener noreferrer",
                      target: "_blank"
                    }, "Learn React")));
}

var make = App;

export {
  logo ,
  make ,
}
/* logo Not a pure module */
