// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Axios from "axios";
import * as React from "react";
import * as $$Promise from "reason-promise/src/js/promise.bs.js";
import LogoSvg from "./logo.svg";

var logo = LogoSvg;

import './App.css';
;

function headers(param) {
  return {
          "Content-Type": "application/json"
        };
}

var config = {
  headers: {
    "Content-Type": "application/json"
  },
  timeout: 5000
};

function fetchData(param) {
  $$Promise.tapError($$Promise.mapOk($$Promise.Js.toResult(Axios.default.get("http://localhost:8081/stock-name?name=데브시스터즈&pageNo=2", config)), (function (param) {
              console.log(param.data);
            })), (function (err) {
          var e = err.response;
          if (e !== undefined && e.status === 404) {
            console.log("Not found");
          } else {
            console.log("an error occured", e);
          }
        }));
}

function App(Props) {
  var match = React.useState(function () {
        return 0;
      });
  var setCount = match[1];
  React.useEffect((function () {
          var intervalId = setInterval((function (param) {
                  Curry._1(setCount, (function (count) {
                          return count + 1;
                        }));
                }), 100);
          return (function (param) {
                    clearInterval(intervalId);
                  });
        }), []);
  return React.createElement("div", {
              className: "App"
            }, React.createElement("header", {
                  className: "App-header"
                }, React.createElement("button", {
                      onClick: (function (e) {
                          fetchData(undefined);
                        })
                    }, "Fetch"), React.createElement("img", {
                      className: "App-logo",
                      alt: "logo",
                      src: logo
                    }), React.createElement("p", undefined, "Edit ", React.createElement("code", undefined, "src/App.jsx"), " and save to reload."), React.createElement("p", undefined, "Page has been open for ", React.createElement("code", undefined, (match[0] / 10).toFixed(1)), " seconds"), React.createElement("a", {
                      className: "App-link",
                      href: "https://reactjs.org",
                      rel: "noopener noreferrer",
                      target: "_blank"
                    }, "Learn React")));
}

var make = App;

export {
  logo ,
  headers ,
  config ,
  fetchData ,
  make ,
}
/* logo Not a pure module */
