// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Axios from "axios";
import * as React from "react";
import * as $$Promise from "reason-promise/src/js/promise.bs.js";
import LogoSvg from "./logo.svg";

var logo = LogoSvg;

import './App.css';
;

function headers(param) {
  return {
          "Content-Type": "application/json"
        };
}

var config = {
  headers: {
    "Content-Type": "application/json"
  },
  timeout: 5000
};

var baseURL = "http://localhost:8000/stockKR/api";

function App(Props) {
  var match = React.useState(function () {
        return "Not Yet";
      });
  var setResult = match[1];
  return React.createElement("div", {
              className: "App"
            }, React.createElement("header", {
                  className: "App-header"
                }, React.createElement("button", {
                      onClick: (function (_e) {
                          $$Promise.tapError($$Promise.mapOk($$Promise.Js.toResult(Axios.default.get(baseURL + "/", config)), (function (param) {
                                      var data = param.data;
                                      console.log(data);
                                      Curry._1(setResult, data.Hi);
                                    })), (function (err) {
                                  var e = err.response;
                                  if (e !== undefined && e.status === 404) {
                                    console.log("Not found");
                                  } else {
                                    console.log("an error occured", e);
                                  }
                                }));
                        })
                    }, "Fetch"), React.createElement("button", {
                      onClick: (function (_e) {
                          Curry._1(setResult, (function (_s) {
                                  return "Cleaned";
                                }));
                        })
                    }, "Clear"), React.createElement("p", undefined, match[0])));
}

var make = App;

export {
  logo ,
  headers ,
  config ,
  baseURL ,
  make ,
}
/* logo Not a pure module */
