// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDom from "react-dom";
import * as App$Restock from "./App.bs.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

import './index.css';
;

console.log("hello world!")
;

ReactDom.render(React.createElement(React.StrictMode, {
          children: React.createElement(App$Restock.make, {})
        }), Belt_Option.getExn(Caml_option.nullable_to_opt(document.querySelector("#root"))));

if (import.meta.hot) {
  import.meta.hot.accept();
}

export {
  
}
/*  Not a pure module */
