// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Axios from "axios";
import * as React from "react";
import * as $$Promise from "reason-promise/src/js/promise.bs.js";
import * as ReactDom from "react-dom";
import * as App$Restock from "./App.bs.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

import './index.css';
;

function headers(param) {
  return {
          "Content-Type": "application/json"
        };
}

var config = {
  headers: {
    "Content-Type": "application/json"
  },
  timeout: 5000
};

function fetchData(param) {
  $$Promise.tapError($$Promise.mapOk($$Promise.Js.toResult(Axios.default.get("http://localhost:8081/stock-name?name=데브시스터즈", config)), (function (param) {
              console.log(param.data);
            })), (function (err) {
          var e = err.response;
          if (e !== undefined && e.status === 404) {
            console.log("Not found");
          } else {
            console.log("an error occured", e);
          }
        }));
}

fetchData(undefined);

ReactDom.render(React.createElement(React.StrictMode, {
          children: React.createElement(App$Restock.make, {})
        }), Belt_Option.getExn(Caml_option.nullable_to_opt(document.querySelector("#root"))));

if (import.meta.hot) {
  import.meta.hot.accept();
}

export {
  headers ,
  config ,
  fetchData ,
}
/*  Not a pure module */
